INFO:root:Contract /dataset/unchecked_low_level_calls/king_of_the_ether_throne.sol:KingOfTheEtherThrone:
INFO:symExec:Running, please wait...
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 302, in propagate_taint
    stack_object = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 302, in propagate_taint
    stack_object = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 128, in propagate_taint
    object = tainted_stack[len(instruction.data_in)-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 128, in propagate_taint
    object = tainted_stack[len(instruction.data_in)-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 302, in propagate_taint
    stack_object = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 302, in propagate_taint
    stack_object = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 302, in propagate_taint
    stack_object = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 302, in propagate_taint
    stack_object = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 302, in propagate_taint
    stack_object = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 302, in propagate_taint
    stack_object = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 302, in propagate_taint
    stack_object = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 302, in propagate_taint
    stack_object = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 128, in propagate_taint
    object = tainted_stack[len(instruction.data_in)-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 128, in propagate_taint
    object = tainted_stack[len(instruction.data_in)-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 136, in propagate_taint
    temp = tainted_stack[len(instruction.data_in)-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 128, in propagate_taint
    object = tainted_stack[len(instruction.data_in)-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 302, in propagate_taint
    stack_object = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 302, in propagate_taint
    stack_object = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 650, in perform_taint_analysis
    check_taint(tainted_stack, tainted_memory, tainted_storage, instruction, sink_flows, arithmetic_errors, previous_block)
  File "/root/osiris/taintFlow.py", line 471, in check_taint
    object = tainted_stack[1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 302, in propagate_taint
    stack_object = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 302, in propagate_taint
    stack_object = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 302, in propagate_taint
    stack_object = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 302, in propagate_taint
    stack_object = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 302, in propagate_taint
    stack_object = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 128, in propagate_taint
    object = tainted_stack[len(instruction.data_in)-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 128, in propagate_taint
    object = tainted_stack[len(instruction.data_in)-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 128, in propagate_taint
    object = tainted_stack[len(instruction.data_in)-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 143, in propagate_taint
    value = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 302, in propagate_taint
    stack_object = tainted_stack.pop(0)
IndexError: pop from empty list
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 128, in propagate_taint
    object = tainted_stack[len(instruction.data_in)-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 128, in propagate_taint
    object = tainted_stack[len(instruction.data_in)-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 128, in propagate_taint
    object = tainted_stack[len(instruction.data_in)-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 143, in propagate_taint
    value = tainted_stack.pop(0)
IndexError: pop from empty list
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 39.0%
INFO:symExec:	  Arithmetic bugs: 	 True
INFO:symExec:	  └> Overflow bugs: 	 True
/dataset/unchecked_low_level_calls/king_of_the_ether_throne.sol:KingOfTheEtherThrone:134:9
pastMonarchs.push(currentMonarch)
^
/dataset/unchecked_low_level_calls/king_of_the_ether_throne.sol:KingOfTheEtherThrone:25:1
contract KingOfTheEtherThrone {
^
/dataset/unchecked_low_level_calls/king_of_the_ether_throne.sol:KingOfTheEtherThrone:134:9
pastMonarchs.push(currentMonarch)
^
INFO:symExec:	  └> Underflow bugs: 	 False
INFO:symExec:	  └> Division bugs: 	 False
INFO:symExec:	  └> Modulo bugs:   	 False
INFO:symExec:	  └> Truncation bugs: 	 False
INFO:symExec:	  └> Signedness bugs: 	 False
INFO:symExec:	  Callstack bug: 	 True
/dataset/unchecked_low_level_calls/king_of_the_ether_throne.sol:KingOfTheEtherThrone:169:9
wizardAddress.send(amount)
^
/dataset/unchecked_low_level_calls/king_of_the_ether_throne.sol:KingOfTheEtherThrone:128:13
currentMonarch.etherAddress.send(compensation)
^
/dataset/unchecked_low_level_calls/king_of_the_ether_throne.sol:KingOfTheEtherThrone:108:13
msg.sender.send(valuePaid)
^
/dataset/unchecked_low_level_calls/king_of_the_ether_throne.sol:KingOfTheEtherThrone:115:13
msg.sender.send(excessPaid)
^
INFO:symExec:	  Concurrency bug: 	 False
INFO:symExec:	  Time dependency bug: 	 False
INFO:symExec:	  Reentrancy bug: 	 False
INFO:symExec:	 --- 50.0827000141 seconds ---
INFO:symExec:	====== Analysis Completed ======

  .oooooo.             o8o            o8o          
 d8P'  `Y8b            `"'            `"'          
888      888  .oooo.o oooo  oooo d8b oooo   .oooo.o
888      888 d88(  "8 `888  `888""8P `888  d88(  "8
888      888 `"Y88b.   888   888      888  `"Y88b. 
`88b    d88' o.  )88b  888   888      888  o.  )88b
 `Y8bood8P'  8""888P' o888o d888b    o888o 8""888P'


Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
Unexpected error: <type 'exceptions.IndexError'>
!!! SYMBOLIC EXECUTION TIMEOUT !!!